# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - 02_ADF/*
pr:
  branches:
    include:
      - master
  paths:
    include:
      - 02_ADF/*

pool:
  name: Azure Pipelines
  demands: azureps
  vmImage: 'vs2017-win2016'
#Your build pipeline references an undefined variable named ‘SASTOKEN’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
variables:
  - group: devops-adf-vg
  - name: containerUri
  - group: devops-iac-vg
  - name: storage
    value: $[replace(variables['BASE_NAME'],'-','')]
  - name: ContainerName
    value: armstage
  - name: adf 


  
steps:
- task: Bash@3
  displayName: Set variable
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
        echo '##vso[task.setvariable variable=storage]$(storage)armsa'
        echo '##vso[task.setvariable variable=containerUri]https://$(storage)armsa.blob.core.windows.net/$(ContainerName)'
        echo '##vso[task.setvariable variable=adf]$(BASE_NAME)-adf'
        
- task: AzureFileCopy@3
  displayName: 'AzureBlob File Copy'
  inputs:
    SourcePath: '02_ADF/linkedTemplates'
    azureSubscription: 'azure-resource-connection'
    Destination: AzureBlob
    storage: $(storage)
    ContainerName: $(ContainerName)



- task: AzureResourceGroupDeployment@2
  displayName: 'Deploy resources to Azure'
  inputs:
    azureSubscription: "$(AZURE_RM_SVC_CONNECTION)"
    action: "Create Or Update Resource Group"
    resourceGroupName: "$(RESOURCE_GROUP)"
    location: $(LOCATION)
    templateLocation: "Linked artifact"
    csmFile: '02_ADF/linkedTemplates/ArmTemplate_master.json'
    deploymentMode: "Incremental"
    overrideParameters: '-factoryName $(adf) -containerSasToken $(ARMStorageSaSToken) -containerUri $(containerUri)'
    